{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE TypeApplications #-}

module Ema.Asset where

-- | The type of assets produced by Ema.
data Asset a
  = -- | A static file that is copied as-is from the source directory.
    AssetStatic FilePath
  | -- | A file whose contents are generated by user code.
    --
    -- If the the file is HTML, then use `Just Html` to inform Ema's live server
    -- of its nature.
    AssetGenerated Format a
  deriving (Eq, Show, Ord, Generic)

data Format = Html | Other
  deriving (Eq, Show, Ord, Generic)
